### ISSUE TITLE
installation hang on updating the database

### ISSUE THREAD

**Issue by minhanh1234** [choupit0/MassVulScan#2]
Hi i am trying to install this package on Ubuntu 22
and the installation hang on Updating the database.

and i am running it as sudo and try sudo -i to root.

**Comment by choupit0** [comment]
> Hi i am trying to install this package on Ubuntu 22 and the installation hang on Updating the database.
> 
> and i am running it as sudo and try sudo -i to root.

Hello, please, could you provide the error message?

**Comment by choupit0** [comment]
No answer -> closed.
